"""Add fields to Appointment model

Revision ID: cd86a183dc71
Revises: 
Create Date: 2025-04-08 12:21:12.211267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd86a183dc71'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_appointment_created_by_id_user', 'user', ['created_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_appointment_created_by_id_user', type_='foreignkey')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('status')
        batch_op.drop_column('location')
        batch_op.drop_column('doctor_name')

    # ### end Alembic commands ###
